// This is an autogenerated file from Firebase Studio.
'use server';

/**
 * @fileOverview Determines the best type of visual representation for the HydroChill bottle's features.
 *
 * - generateProductVisuals - A function that analyzes product information and design specifications to
 *   determine the best visual representation (e.g., 3D model, interactive graphic).
 * - GenerateProductVisualsInput - The input type for the generateProductVisuals function.
 * - GenerateProductVisualsOutput - The return type for the generateProductVisuals function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateProductVisualsInputSchema = z.object({
  productDescription: z
    .string()
    .describe('Detailed description of the HydroChill bottle and its features.'),
  designSpecifications: z
    .string()
    .describe('Technical design specifications of the HydroChill bottle.'),
});
export type GenerateProductVisualsInput = z.infer<typeof GenerateProductVisualsInputSchema>;

const GenerateProductVisualsOutputSchema = z.object({
  visualType: z
    .string()
    .describe(
      'The recommended type of visual representation for the HydroChill bottle (e.g., 3D model, interactive graphic).'
    ),
  rationale: z
    .string()
    .describe('The rationale behind the recommended visual representation type.'),
  additionalNotes: z
    .string()
    .optional()
    .describe('Any additional notes or considerations for creating the visual.'),
});
export type GenerateProductVisualsOutput = z.infer<typeof GenerateProductVisualsOutputSchema>;

export async function generateProductVisuals(
  input: GenerateProductVisualsInput
): Promise<GenerateProductVisualsOutput> {
  return generateProductVisualsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'generateProductVisualsPrompt',
  input: {schema: GenerateProductVisualsInputSchema},
  output: {schema: GenerateProductVisualsOutputSchema},
  prompt: `You are an expert in product visualization and marketing.

  Given the following product description and design specifications for the HydroChill bottle, analyze the information and determine the best type of visual representation to showcase its features to potential customers.

  Consider the following visual types:
  - 3D Model: An interactive 3D model of the bottle.
  - Interactive Graphic: An animated graphic that highlights the bottle's key features.
  - Exploded View: A visual representation showing the bottle's components separately.
  - Lifestyle Imagery: Images of the bottle in various real-world scenarios.

  Product Description: {{{productDescription}}}
  Design Specifications: {{{designSpecifications}}}

  Based on your analysis, recommend a visual type and provide a rationale for your recommendation. Also, include any additional notes or considerations for creating the visual.

  Ensure the output is formatted correctly according to the GenerateProductVisualsOutputSchema schema.`,
});

const generateProductVisualsFlow = ai.defineFlow(
  {
    name: 'generateProductVisualsFlow',
    inputSchema: GenerateProductVisualsInputSchema,
    outputSchema: GenerateProductVisualsOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    return output!;
  }
);
